// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqcmannhdhaavunhobuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxY21hbm5oZGhhYXZ1bmhvYnVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjUzOTYsImV4cCI6MjA2MjIwMTM5Nn0.hiUk0_se8N_rA_7HaaVdMry2I5GVtU_1qZDhw4PGKeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);